import React from "react";
import type { NextPage } from "next";
import { useAppContext } from "../contexts/AppContext";
import Head from "next/head";
import ProductsTable from "../components/modules/ProductsTable/ProductsTable";
import OrderSummary from "../components/modules/OrderSummary/OrderSummary";
import styles from "../styles/Cart.module.scss";

const Cart: NextPage = () => {
  const { products, checkout, modal } = useAppContext();

  return (
    <div className={styles.Cart}>
      <Head>
        <title>Cart | Cabify Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${styles.main} ${modal ? styles["main-hasModal"] : ""}`}
      >
        {modal && modal}
        <section className={styles.products}>
          <h1>Shopping cart</h1>
          <ProductsTable products={products} checkout={checkout} />
        </section>
        <OrderSummary />
      </main>
    </div>
  );
};

export default Cart;
